# Generated by Django 5.1.4 on 2025-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzdatum',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzdatum',
            name='base_fair',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzdatum',
            name='currency_amount',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzdatum',
            name='currency_rate',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzdatum',
            name='store_amount',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
    ]
